### ISSUE TITLE
Bogus syntax error crashes pgspot

### ISSUE THREAD

**Issue by jgpruitt** [timescale/pgspot#196]
The file `bob.sql` is as below:
```sql
create or replace function bob() returns void as $func$
declare
	_count bigint;
begin
	select 100 into strict _count;
	while 0 < _count loop
		select _count - 1 into strict _count;
	end loop;
end
$func$ language plpgsql volatile security invoker
set search_path to pg_catalog, pg_temp
;
```
If I run `pgspot bob.sql`, I get the following:
```text
PS002: Unsafe function creation: bob() at line 1

 Errors: 1 Warnings: 0 Unknown: 0 
 syntax error at or near "0", at index 0
```
The `syntax error at or near "0", at index 0` causes pgspot to fail. I can run this code in Postgres 16 and it works fine -- no syntax error. I have tried several variations on the loop logic, and pgspot has syntax errors with all of them. I have tried pgspot 0.8.0 and the main branch, and both have the same result.

I can't figure out what is causing the syntax error.

**Comment by jgpruitt** [comment]
I also get the error with v0.7.1

**Comment by svenklemm** [comment]
Hmm looks like a bug in pgspot, the plpgsql parses fine in pglast
