### ISSUE TITLE
Add option to return an error on empty input file

### ISSUE THREAD

**Issue by jnidzwetzki** [timescale/pgspot#41]
At the moment, `pgspot` does not distinguish between correct and empty input files. In some environments (e.g., a CI pipeline where the files that are processed by `pgspot` are automatically generated) it would be helpful when `pgspot` would support an option and return an error code, if an empty file is passed as argument (e.g., `--fail-on-empty-input-file`). This behavior would ensure that `pgspot` actually processes some statements and build errors that lead to empty input files can be captured in a CI pipeline.

**Comment by svenklemm** [comment]
Not sure this needs to be part of pgspot.
